#%RAML 1.0
title: SFTP System API
version: 1.0.0
description: API for retrieving and transforming invoice data from SFTP for the finance department.

uses:
 # types: dataType.raml
 paradisoLibrary: /exchange_modules/4e7e9d23-3711-4be5-a59f-f45b7e8b0531/paradiso-project/1.0.2/paradiso-library.raml
/invoices:
  get:
    description: Retrieve all invoices from the SFTP server.
    queryParameters:
      currency:
        description: Filter by currency (USD and EUR accepted).
        type: string
        enum: [USD, EUR]
        required: false
    responses:
      200:
        body:
          application/json:
           
           
      400:
        description: Bad Request - Returned if the currency is invalid.
        body:
          application/json:
           

  /{id}:
    get:
      description: Retrieve a single invoice by its ID.
      responses:
        200:
          body:
              application/json:
types:
  Product:
      type: object
      properties:
        id:
          type: number
          description: Unique product identifier.
        name:
          type: string
          description: Name of the product.
        category:
          type: string
          enum: [Accessoire, Audio, Électronique, Graphisme, Sécurité]
          description: The category of the product.
        price:
          type: number
          description: Unit price.
        stock:
          type: number
          description: Quantity in stock.
/products:
  get:
    description: Retrieve products with optional category filtering.
    queryParameters:
      category:
        type: string
        required: false
        enum: [Accessoire, Audio, Électronique, Graphisme, Sécurité]
    responses:
      200:
        body:
          application/json:
            type: paradisoLibrary.standardSuccess
            properties:
              data:
                type: Product[]

  post:
    description: Create a new product entry.
    body:
      application/json:
        type: Product
    responses:
      201:
        description: Product created.
        body:
          application/json:
            type: paradisoLibrary.standardSuccess
            properties:
              statusCode:
                type: integer
                example: 201
      406:
        body:
          application/json:
            properties:
              message:
                type: string
                example: "Product ID already exists"

  /{id}:
    uriParameters:
      id:
        type: string
    post:
      description: Increment product stock by 1 for a specific ID.
      responses:
        201:
          body:
            application/json:
              type: paradisoLibrary.standardSuccess
              properties:
                statusCode:
                  type: integer
                  example: 201
                message:
                  type: string
                  example: "Stock incremented successfully"
        404:
          body:
            application/json:
              properties:
                message:
                  type: string
                  example: "Product ID not found"

    delete:
      description: Remove a product or decrement stock for a specific ID.
      queryParameters:
        qty:
          type: number
          required: false
      responses:
        204:
          description: Success.
          body:
            application/json:
              type: paradisoLibrary.standardSuccess
              properties:
                statusCode:
                  type: integer
                  example: 204
                message:
                  type: string
                  example: "Product or stock successfully removed"
        404:
          body:
            application/json:
              properties:
                message:
                  type: string
                  example: "Product ID not found"